# Generated by Django 6.0.5 on 2026-05-28 16:34

from decimal import Decimal

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpOffice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("reference", models.CharField(editable=False, max_length=20, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("national_number", models.CharField(blank=True, max_length=40)),
                ("current_address", models.CharField(blank=True, max_length=255)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("self_employed", "Self-employed"),
                            ("civil_servant", "Civil servant"),
                            ("retired", "Retired"),
                            ("other", "Other"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("decide_application", "Can approve or reject an application")],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("flagged", "Flagged"),
                            ("failed", "Analysis failed"),
                        ],
                        default="uploaded",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("id_card", "Identity card"),
                            ("payslip", "Payslip"),
                            ("epc_certificate", "EPC certificate"),
                            ("sales_agreement", "Sales agreement"),
                            ("bank_statement", "Bank statement"),
                            ("other", "Other supporting document"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="portal.application"
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "detected_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("id_card", "Identity card"),
                            ("payslip", "Payslip"),
                            ("epc_certificate", "EPC certificate"),
                            ("sales_agreement", "Sales agreement"),
                            ("bank_statement", "Bank statement"),
                            ("other", "Other supporting document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("extracted_fields", models.JSONField(default=dict)),
                ("mismatches", models.JSONField(default=list)),
                ("is_stub", models.BooleanField(default=True)),
                ("model_used", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="analysis", to="portal.document"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("converted", "Converted to application"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("reference", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("buy", "Buy a property"),
                            ("build", "Build a new property"),
                            ("buy_out", "Buy out"),
                            ("renovate", "Renovate my property"),
                            ("refinance", "Refinance my mortgage"),
                        ],
                        default="buy",
                        max_length=20,
                    ),
                ),
                ("borrower_count", models.IntegerField(choices=[(1, "Alone"), (2, "With someone")], default=1)),
                (
                    "property_type",
                    models.CharField(
                        choices=[("house", "House"), ("apartment", "Apartment"), ("land", "Building land")],
                        default="house",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("flanders", "Flanders"), ("wallonia", "Wallonia"), ("brussels", "Brussels")],
                        default="flanders",
                        max_length=20,
                    ),
                ),
                ("property_price", models.DecimalField(decimal_places=2, default=Decimal("300000.00"), max_digits=12)),
                (
                    "property_usage",
                    models.CharField(
                        choices=[
                            ("own_home", "Own and only home"),
                            ("second_home", "Second home"),
                            ("investment", "Investment property"),
                        ],
                        default="own_home",
                        max_length=20,
                    ),
                ),
                ("own_funds", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("duration_years", models.IntegerField(default=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("dependents", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomeLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary (employee)"),
                            ("self_employed", "Self-employed / business owner"),
                            ("rental", "Rental income"),
                            ("replacement", "Replacement income"),
                            ("other", "Other"),
                        ],
                        default="salary",
                        max_length=20,
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("borrower_index", models.IntegerField(default=1)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="incomes", to="portal.simulation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("existing_loan", "Existing loan"),
                            ("rent", "Rent"),
                            ("alimony", "Alimony"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="portal.simulation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="simulation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="application", to="portal.simulation"
            ),
        ),
    ]
